/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             2195,
                                             766,
                                             "Zone Test",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             Dialog1HelpButton_CB);
  ExpandZone_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                    338,
                                    92,
                                    1548,
                                    141,
                    "Expand Zone",
                    ExpandZone_BTN_D1_CB);

  ShrinkZone_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                    338,
                                    294,
                                    1535,
                                    141,
                    "Shrink Zone  ",
                    ShrinkZone_BTN_D1_CB);

  RefineMesh_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                    338,
                                    501,
                                    1535,
                                    141,
                    "Refine Mesh ",
                    RefineMesh_BTN_D1_CB);

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
