/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#include "TECADDON.h"
#include "GUIDEFS.h"
LgIndex_t Dialog1Manager = BADDIALOGID;
LgIndex_t ExpandZone_BTN_D1 = BADDIALOGID;
LgIndex_t ShrinkZone_BTN_D1 = BADDIALOGID;
LgIndex_t RefineMesh_BTN_D1 = BADDIALOGID;
