/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


void BuildDialog1(int  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             5073,
                                             633,
                                             "Equate",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             Dialog1HelpButton_CB);
  Multiplyby_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                   496,
                                   133,
                    "Multiply by:");
  MulNum_TF_D1 = TecGUITextFieldAdd(Dialog1Manager,
                                  1795,
                                  90,
                                  1464,
                                  154,
                       MulNum_TF_D1_CB);
  Compute_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                 343,
                                 367,
                                 1146,
                                 154,
                    "Compute",
                    Compute_BTN_D1_CB);
}

void InitTGB(void)
{
/* Currently not used */
}
