/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern int  Dialog1Manager;
extern void BuildDialog1(int  ParentDialog);

extern int  Sidebar_RADIO_D1;
extern int  Sidebar3Manager;
extern void BuildSidebar3(void);
extern int  Show_TOG_S3;
extern int  ShadeTools_LBL_S3;
extern int  Sidebar2Manager;
extern void BuildSidebar2(void);
extern int  Show_TOG_S2;
extern int  Type_OPT_S2;
extern int  CountourTools_LBL_S2;
extern int  Sidebar1Manager;
extern void BuildSidebar1(void);
extern int  MeshTools_LBL_S1;
extern int  Black_BB_S1;
extern int  Blue_BB_S1;
extern int  Gray_BB_S1;
extern int  Green_BB_S1;
extern int  Purple_BB_S1;
extern int  Red_BB_S1;
extern int  White_BB_S1;
extern int  Yellow_BB_S1;
extern int  Show_TOG_S1;
extern int  Type_OPT_S1;
extern int  LinePattern_LBL_S1;
extern int  LinePattern_OPT_S1;
extern int  PatternLength_LBL_S1;
extern int  PatternLength_TF_S1;
extern int  Linethickness_LBL_S1;
extern int  LineThickness_TF_S1;
