/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#include "TECADDON.h"
#include "GUIDEFS.h"
int Dialog1Manager = BADDIALOGID;
int Sidebar_RADIO_D1 = BADDIALOGID;
int Sidebar3Manager = BADDIALOGID;
int Show_TOG_S3 = BADDIALOGID;
int ShadeTools_LBL_S3 = BADDIALOGID;
int Sidebar2Manager = BADDIALOGID;
int Show_TOG_S2 = BADDIALOGID;
int Type_OPT_S2 = BADDIALOGID;
int CountourTools_LBL_S2 = BADDIALOGID;
int Sidebar1Manager = BADDIALOGID;
int MeshTools_LBL_S1 = BADDIALOGID;
int Black_BB_S1 = BADDIALOGID;
int Blue_BB_S1 = BADDIALOGID;
int Gray_BB_S1 = BADDIALOGID;
int Green_BB_S1 = BADDIALOGID;
int Purple_BB_S1 = BADDIALOGID;
int Red_BB_S1 = BADDIALOGID;
int White_BB_S1 = BADDIALOGID;
int Yellow_BB_S1 = BADDIALOGID;
int Show_TOG_S1 = BADDIALOGID;
int Type_OPT_S1 = BADDIALOGID;
int LinePattern_LBL_S1 = BADDIALOGID;
int LinePattern_OPT_S1 = BADDIALOGID;
int PatternLength_LBL_S1 = BADDIALOGID;
int PatternLength_TF_S1 = BADDIALOGID;
int Linethickness_LBL_S1 = BADDIALOGID;
int LineThickness_TF_S1 = BADDIALOGID;
