#!/bin/sh

FCOMPILER=f77
FFLAGS=
CCOMPILER=c89
EXTRALIBS=


USEBACKC=`echo "\c" | wc -c`
if test $USEBACKC -eq 0 ; then
  EFLAG=
  BACKC="\c"
else
  EFLAG=-n
  BACKC=
fi

if test $# -ge 2 ; then
  Model=$1
  TECLIBDIR=..
  INCDIR=../tecsrc
  BuildWhat=$2
  shift 
  shift
else
  if test "$TEC100HOME" = "" ; then
    echo "Must have TEC100HOME environment variable set"
    exit
  fi
  TECLIBDIR=$TEC100HOME/lib
  INCDIR=$TEC100HOME/include
fi

if test $# -eq 0 ; then 
  echo 'Choose the model to build:'
  echo "  sgix.65"
  echo "  sgix64.65"
  echo "  ibmx64.51"
  echo "  hp7xx.11"
  echo "  hp7xx64.11"
  echo "  sun4.57"
  echo "  sun464.57"
  echo "  linux.24"
  echo "  linux64.24"
  echo "  ALL"

  echo $EFLAG "--> $BACKC"

  read Model
fi




case $Model in
  sgix64.65) CFLAGS="-DIRIS -64 -mips4"
             FFLAGS="-64 -mips4";;
  sgix.65)   CFLAGS="-DIRIS -n32 -mips4"
             FFLAGS="-n32 -mips4";;
  ibmx64*)   CFLAGS="-DIBMRS6000 -q64"
             FFLAGS="-q64";;
  ibmx*)     CFLAGS="-DIBMRS6000"
             FFLAGS=;;
  hp7xx64*)  CFLAGS="-DHP +DA2.0W +DD64 +DS2.0W"
             FFLAGS="+DA2.0W +DD64 +DS2.0W"
             FCOMPILER=f90;;
  hp7xx*)    CFLAGS="-DHP +DAportable"
             FFLAGS="+DAportable"
             FCOMPILER=f90;;
  sun464*)   CFLAGS="-DSUN -xarch=v9"
             FFLAGS="-xarch=v9";;
  sun4*)     CFLAGS="-DSUN";;
  linux*)    CCOMPILER=gcc
             CFLAGS="-DLINUX"
             EXTRALIBS=-lstdc++;;
  macx*)     CFLAGS="-DDARWIN"
             FFLAGS=
             EXTRALIBS=-lstdc++;;
  *) echo "Invalid platform: $Model"
     exit;;
esac

case $Model in
  *64.*) TECLIBNAME=tecio64.a;;
      *) TECLIBNAME=tecio.a;;
esac


TECLIB=$TECLIBDIR/$TECLIBNAME


if test $# -eq 0 ; then
  echo "Choose test to build"
  echo " 1.  Simple C example"
  echo " 2.  Simple FORTRAN example"
  echo " 3.  Complex C example"
  echo " 4.  Complex FORTRAN example"
  echo " "

  read BuildWhat
fi


case $BuildWhat in
  1) $CCOMPILER -I.. -I$INCDIR $CFLAGS $* simtest.c $TECLIB -lm $EXTRALIBS -o simtest;;
  2) $FCOMPILER $FFLAGS $*    simtest.f $TECLIB -lm -o $EXTRALIBS simtest;;
  3) $CCOMPILER -I.. -I$INCDIR $CFLAGS comtest.c $TECLIB -lm -o $EXTRALIBS comtest;;
  4) $FCOMPILER $FFLAGS $*    comtest.f $* $TECLIB -lm -o $EXTRALIBS comtest;;
esac
