      INTEGER*4 FUNCTION tecini100

      INTEGER*4 FUNCTION teczne100

      INTEGER*4 FUNCTION tecdat100

      INTEGER*4 FUNCTION tecnod100

      INTEGER*4 FUNCTION tecend 100

      INTEGER*4 FUNCTION teclab100

      INTEGER*4 FUNCTION tecusr100

      INTEGER*4 FUNCTION tecgeo100

      INTEGER*4 FUNCTION tectxt100

      INTEGER*4 FUNCTION tecfil100
      
      INTEGER*4 FUNCTION tecauxstr100
      
      INTEGER*4 FUNCTION teczauxstr100
      
      INTEGER*4 FUNCTION tecface100

      INTEGER*4 FUNCTION tecini

      INTEGER*4 FUNCTION teczne

      INTEGER*4 FUNCTION tecdat

      INTEGER*4 FUNCTION tecnod

      INTEGER*4 FUNCTION tecend 

      INTEGER*4 FUNCTION teclab

      INTEGER*4 FUNCTION tecusr

      INTEGER*4 FUNCTION tecgeo

      INTEGER*4 FUNCTION tectxt

      INTEGER*4 FUNCTION tecfil
