/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



void BuildDialog2(int  ParentDialog)
{
  if (Dialog2Manager != BADDIALOGID)
    return;

  Dialog2Manager = TecGUIDialogCreateModal(ParentDialog,
                                          4383,
                                          2249,
                                          "Untitled",
                                          Dialog2Init_CB,
                                          Dialog2OkButton_CB,
                                          NULL,
                                          Dialog2CancelButton_CB,
                                          Dialog2HelpButton_CB);
  GoAhead_BTN_D2 = TecGUIButtonAdd(Dialog2Manager,
                                 1604,
                                 553,
                                 1235,
                                 151,
                    "Go Ahead",
                    GoAhead_BTN_D2_CB);
}


void BuildDialog1(int  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             4383,
                                             2249,
                                             "Some Dialog",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             Dialog1HelpButton_CB);
}

void InitTGB(void)
{
/* Currently not used */
}
