/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#include "TECADDON.h"
#include "GUIDEFS.h"
int Dialog2Manager = BADDIALOGID;
int GoAhead_BTN_D2 = BADDIALOGID;
int Dialog1Manager = BADDIALOGID;
