/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern int  Dialog2Manager;
extern void BuildDialog2(int  ParentDialog);

extern int  GoAhead_BTN_D2;
extern int  Dialog1Manager;
extern void BuildDialog1(int  ParentDialog);

