/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



void BuildDialog1(int  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModal(ParentDialog,
                                          4383,
                                          865,
                                          "Simple Average",
                                          Dialog1Init_CB,
                                          Dialog1OkButton_CB,
                                          NULL,
                                          Dialog1CancelButton_CB,
                                          Dialog1HelpButton_CB);
  Min_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                            863,
                            427,
                    "Min   ");
  Max_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                            848,
                            635,
                    "Max   ");
  IndVarMin_TF_D1 = TecGUITextFieldAdd(Dialog1Manager,
                                     1598,
                                     392,
                                     1245,
                                     154,
                       IndVarMin_TF_D1_CB);
  IndVarMax_TF_D1 = TecGUITextFieldAdd(Dialog1Manager,
                                     1598,
                                     600,
                                     1245,
                                     154,
                       IndVarMax_TF_D1_CB);
  UseIndVarRan_TOG_D1 = TecGUIToggleAdd(Dialog1Manager,
                                      311,
                                      154,
                                      4046,
                                      118,
                               "Use Independent Variable Range",
                               UseIndVarRan_TOG_D1_CB);
}

void InitTGB(void)
{
/* Currently not used */
}
