/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#include "TECADDON.h"
#include "GUIDEFS.h"
int Dialog1Manager = BADDIALOGID;
int Min_LBL_D1 = BADDIALOGID;
int Max_LBL_D1 = BADDIALOGID;
int IndVarMin_TF_D1 = BADDIALOGID;
int IndVarMax_TF_D1 = BADDIALOGID;
int UseIndVarRan_TOG_D1 = BADDIALOGID;
