/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             4655,
                                             2853,
                                             "Timer Test",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             Dialog1HelpButton_CB);
  Timers_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                               195,
                               59,
                    "Timers:");

  Timers_SLST_D1 = TecGUIListAdd(Dialog1Manager,
                               195,
                               196,
                               4202,
                               1873,
                       0,
                       Timers_SLST_D1_CB);

  CallCountLabel_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                       195,
                                       2309,
                    "Call count");

  CallCountField_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                       1756,
                                       2309,
                    "XXXXX");

  Active_TOG_D1 = TecGUIToggleAdd(Dialog1Manager,
                                1756,
                                2118,
                                1288,
                                114,
                               "Active",
                               Active_TOG_D1_CB);

  TimerStatusLabel_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                         195,
                                         2145,
                    "Timer status:");

  LockCountLabel_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                       195,
                                       2472,
                    "Lock count:");

  LockCountField_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                       1756,
                                       2472,
                    "XXXXX");

  LockOwnerLabel_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                       195,
                                       2635,
                    "Lock owner:");

  LockOwnerField_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                       1756,
                                       2635,
                    "XXXXX");

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
