/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern LgIndex_t Dialog1Manager;
extern void BuildDialog1(LgIndex_t  ParentDialog);

extern LgIndex_t  Timers_LBL_D1;
extern LgIndex_t  Timers_SLST_D1;
extern LgIndex_t  CallCountLabel_LBL_D1;
extern LgIndex_t  CallCountField_LBL_D1;
extern LgIndex_t  Active_TOG_D1;
extern LgIndex_t  TimerStatusLabel_LBL_D1;
extern LgIndex_t  LockCountLabel_LBL_D1;
extern LgIndex_t  LockCountField_LBL_D1;
extern LgIndex_t  LockOwnerLabel_LBL_D1;
extern LgIndex_t  LockOwnerField_LBL_D1;
