/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#include "TECADDON.h"
#include "GUIDEFS.h"
LgIndex_t Dialog1Manager = BADDIALOGID;
LgIndex_t Timers_LBL_D1 = BADDIALOGID;
LgIndex_t Timers_SLST_D1 = BADDIALOGID;
LgIndex_t CallCountLabel_LBL_D1 = BADDIALOGID;
LgIndex_t CallCountField_LBL_D1 = BADDIALOGID;
LgIndex_t Active_TOG_D1 = BADDIALOGID;
LgIndex_t TimerStatusLabel_LBL_D1 = BADDIALOGID;
LgIndex_t LockCountLabel_LBL_D1 = BADDIALOGID;
LgIndex_t LockCountField_LBL_D1 = BADDIALOGID;
LgIndex_t LockOwnerLabel_LBL_D1 = BADDIALOGID;
LgIndex_t LockOwnerField_LBL_D1 = BADDIALOGID;
