/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildTab1_1(LgIndex_t  Parent)
{
  if (Tab1_1Manager != BADDIALOGID)
    return;

  Tab1_1Manager = TecGUITabAddPage(Parent,
                               "Specific");
  Offset1_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                  4479,
                                  348,
                    "Offset1");

  Offset2_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                  4479,
                                  633,
                    "Offset2");

  S1_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                             4927,
                             991,
                    "S1");

  S2_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                             4927,
                             1267,
                    "S2");

  S3_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                             4927,
                             1553,
                    "S3");

  S4_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                             4927,
                             1830,
                    "S4");

  S5_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                             4927,
                             2116,
                    "S5");

  S6_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                             4927,
                             2401,
                    "S6");

  Units_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                8340,
                                2776,
                    "N/A");

  GetValue_BTN_T1_1 = TecGUIButtonAdd(Tab1_1Manager,
                                    4010,
                                    2741,
                                    1194,
                                    142,
                    "Get Value",
                    GetValue_BTN_T1_1_CB);

  Offset1Value_TF_T1_1 = TecGUITextFieldAdd(Tab1_1Manager,
                                          5375,
                                          303,
                                          2772,
                                          142,
                       Offset1Value_TF_T1_1_CB);

  Offset2Value_TF_T1_1 = TecGUITextFieldAdd(Tab1_1Manager,
                                          5375,
                                          589,
                                          2772,
                                          142,
                       Offset2Value_TF_T1_1_CB);

  S1Value_TF_T1_1 = TecGUITextFieldAdd(Tab1_1Manager,
                                     5375,
                                     946,
                                     2772,
                                     142,
                       S1Value_TF_T1_1_CB);

  S2Value_TF_T1_1 = TecGUITextFieldAdd(Tab1_1Manager,
                                     5375,
                                     1232,
                                     2772,
                                     142,
                       S2Value_TF_T1_1_CB);

  S3Value_TF_T1_1 = TecGUITextFieldAdd(Tab1_1Manager,
                                     5375,
                                     1508,
                                     2772,
                                     142,
                       S3Value_TF_T1_1_CB);

  S4Value_TF_T1_1 = TecGUITextFieldAdd(Tab1_1Manager,
                                     5375,
                                     1794,
                                     2772,
                                     142,
                       S4Value_TF_T1_1_CB);

  S5Value_TF_T1_1 = TecGUITextFieldAdd(Tab1_1Manager,
                                     5375,
                                     2071,
                                     2772,
                                     142,
                       S5Value_TF_T1_1_CB);

  S6Value_TF_T1_1 = TecGUITextFieldAdd(Tab1_1Manager,
                                     5375,
                                     2357,
                                     2772,
                                     142,
                       S6Value_TF_T1_1_CB);

  GetValueResul_TF_T1_1 = TecGUITextFieldAdd(Tab1_1Manager,
                                           5375,
                                           2741,
                                           2772,
                                           142,
                       GetValueResul_TF_T1_1_CB);

}

/**
 */
void BuildTab2_1(LgIndex_t  Parent)
{
  if (Tab2_1Manager != BADDIALOGID)
    return;

  Tab2_1Manager = TecGUITabAddPage(Parent,
                               "Zone/Map");
  Styleattribu_LBL_T2_1 = TecGUILabelAdd(Tab2_1Manager,
                                       341,
                                       98,
                    "Style attributes for zone or map:");

  ZoneOrMap_TFS_T2_1 = TecGUISpinTextFieldAdd(Tab2_1Manager,
                                            3668,
                                            62,
                                            1151,
                                            142,
                       ZoneOrMap_TFS_T2_1_ValueChanged_CB,
                       ZoneOrMap_TFS_T2_1_ButtonUp_CB,
                       ZoneOrMap_TFS_T2_1_ButtonDown_CB);

  StyleResult_T_T2_1 = TecGUITextAdd(Tab2_1Manager,
                                   277,
                                   258,
                                   14013,
                                   3053,
                       1,
                       NULL);

}

/**
 */
void BuildTab3_1(LgIndex_t  Parent)
{
  if (Tab3_1Manager != BADDIALOGID)
    return;

  Tab3_1Manager = TecGUITabAddPage(Parent,
                               "Global Style");
  LBL1_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                               341,
                               98,
                    "Global Style:");

  GlobalStyle_T_T3_1 = TecGUITextAdd(Tab3_1Manager,
                                   277,
                                   258,
                                   14013,
                                   3053,
                       1,
                       NULL);

}

/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             14942,
                                             3774,
                                             "Get Style Exerciser",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             Dialog1HelpButton_CB);
  TAB1_TB_D1 = TecGUITabAdd(Dialog1Manager,
                          213,
                          241,
                          14525,
                          3419,
                    TAB1_TBA_D1_CB,
                    TAB1_TBD_D1_CB);

  BuildTab1_1(TAB1_TB_D1);
  BuildTab2_1(TAB1_TB_D1);
  BuildTab3_1(TAB1_TB_D1);
}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
