/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern LgIndex_t Tab1_1Manager;
extern void BuildTab1_1(LgIndex_t  Parent);

extern LgIndex_t  Offset1_LBL_T1_1;
extern LgIndex_t  Offset2_LBL_T1_1;
extern LgIndex_t  S1_LBL_T1_1;
extern LgIndex_t  S2_LBL_T1_1;
extern LgIndex_t  S3_LBL_T1_1;
extern LgIndex_t  S4_LBL_T1_1;
extern LgIndex_t  S5_LBL_T1_1;
extern LgIndex_t  S6_LBL_T1_1;
extern LgIndex_t  Units_LBL_T1_1;
extern LgIndex_t  GetValue_BTN_T1_1;
extern LgIndex_t  Offset1Value_TF_T1_1;
extern LgIndex_t  Offset2Value_TF_T1_1;
extern LgIndex_t  S1Value_TF_T1_1;
extern LgIndex_t  S2Value_TF_T1_1;
extern LgIndex_t  S3Value_TF_T1_1;
extern LgIndex_t  S4Value_TF_T1_1;
extern LgIndex_t  S5Value_TF_T1_1;
extern LgIndex_t  S6Value_TF_T1_1;
extern LgIndex_t  GetValueResul_TF_T1_1;
extern LgIndex_t Tab2_1Manager;
extern void BuildTab2_1(LgIndex_t  Parent);

extern LgIndex_t  Styleattribu_LBL_T2_1;
extern LgIndex_t  ZoneOrMap_TFS_T2_1;
extern LgIndex_t  StyleResult_T_T2_1;
extern LgIndex_t Tab3_1Manager;
extern void BuildTab3_1(LgIndex_t  Parent);

extern LgIndex_t  LBL1_LBL_T3_1;
extern LgIndex_t  GlobalStyle_T_T3_1;
extern LgIndex_t Dialog1Manager;
extern void BuildDialog1(LgIndex_t  ParentDialog);

extern LgIndex_t  TAB1_TB_D1;
