      EXTERNAL Dialog1HelpButton_CB
      !DEC$ attributes C::Dialog1HelpButton_CB
      EXTERNAL Dialog1CancelButton_CB
      !DEC$ attributes C::Dialog1CancelButton_CB
      EXTERNAL Dialog1OkButton_CB
      !DEC$ attributes C::Dialog1OkButton_CB
      EXTERNAL Dialog1Init_CB
      !DEC$ attributes C::Dialog1Init_CB
      EXTERNAL FName_TF_D1_CB
      INTEGER FName_TF_D1_CB
      !DEC$ attributes C::FName_TF_D1_CB
      EXTERNAL Skip_TF_D1_CB
      INTEGER Skip_TF_D1_CB
      !DEC$ attributes C::Skip_TF_D1_CB
      EXTERNAL Browse_BTN_D1_CB
      !DEC$ attributes C::Browse_BTN_D1_CB
