/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             7248,
                                             2249,
                                             "key Event",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             Dialog1HelpButton_CB);
  KeyResult_T_D1 = TecGUITextAdd(Dialog1Manager,
                               3642,
                               151,
                               2394,
                               1963,
                       0,
                       KeyResult_T_D1_CB);

  LBL2_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             3705,
                             45,
                    "Resulting Keystrokes:");

  TFSrc_TF_D1 = TecGUITextFieldAdd(Dialog1Manager,
                                 165,
                                 589,
                                 1222,
                                 146,
                       TFSrc_TF_D1_CB);

  TSrc_T_D1 = TecGUITextAdd(Dialog1Manager,
                          165,
                          1238,
                          2228,
                          780,
                       0,
                       TSrc_T_D1_CB);

  LBL5_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             165,
                             498,
                    "Enter values in textfield:");

  LBL6_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             165,
                             1047,
                    "Enter values in Multi-line");

  LBL7_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             165,
                             1148,
                    "Text Field:");

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
