/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#include "TECADDON.h"
#include "GUIDEFS.h"
LgIndex_t Dialog1Manager = BADDIALOGID;
LgIndex_t KeyResult_T_D1 = BADDIALOGID;
LgIndex_t LBL2_LBL_D1 = BADDIALOGID;
LgIndex_t TFSrc_TF_D1 = BADDIALOGID;
LgIndex_t TSrc_T_D1 = BADDIALOGID;
LgIndex_t LBL5_LBL_D1 = BADDIALOGID;
LgIndex_t LBL6_LBL_D1 = BADDIALOGID;
LgIndex_t LBL7_LBL_D1 = BADDIALOGID;
