/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             2481,
                                             847,
                                             "Circle Stream",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             Dialog1HelpButton_CB);
  AddStreamtra_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                      203,
                                      101,
                                      2012,
                                      143,
                    "Add Streamtraces",
                    AddStreamtra_BTN_D1_CB);

  RadioButto_RADIO_D1 = TecGUIRadioBoxAdd(Dialog1Manager,
                                        229,
                                        298,
                                        1566,
                                        437,
                                 "Forwards",
                                 "Backwards",
                                 "Both",
                                 (char *)NULL,
                                 (char *)NULL,
                                 RadioButto_RADIO_D1_CB);

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
