/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


void BuildForm1_3(int  Parent)
{
  if (Form1_3Manager != BADDIALOGID)
    return;

  Form1_3Manager = TecGUIFormAddPage(Parent);

  Homer_LBL_F1_3 = TecGUILabelAdd(Form1_3Manager,
                                373,
                                108,
                    "Homer");
  Apples_TOG_F1_3 = TecGUIToggleAdd(Form1_3Manager,
                                  373,
                                  239,
                                  1217,
                                  92,
                               "  Apples",
                               Apples_TOG_F1_3_CB);
  Oranges_TOG_F1_3 = TecGUIToggleAdd(Form1_3Manager,
                                   373,
                                   359,
                                   1383,
                                   92,
                               "  Oranges",
                               Oranges_TOG_F1_3_CB);
}

void BuildForm2_3(int  Parent)
{
  if (Form2_3Manager != BADDIALOGID)
    return;

  Form2_3Manager = TecGUIFormAddPage(Parent);

  Marge_LBL_F2_3 = TecGUILabelAdd(Form2_3Manager,
                                276,
                                87,
                    "Marge");
  Apples_BTN_F2_3 = TecGUIButtonAdd(Form2_3Manager,
                                  248,
                                  196,
                                  912,
                                  152,
                    "Apples",
                    Apples_BTN_F2_3_CB);
  Oranges_BTN_F2_3 = TecGUIButtonAdd(Form2_3Manager,
                                   248,
                                   397,
                                   1078,
                                   152,
                    "Oranges",
                    Oranges_BTN_F2_3_CB);
}

void BuildForm3_3(int  Parent)
{
  if (Form3_3Manager != BADDIALOGID)
    return;

  Form3_3Manager = TecGUIFormAddPage(Parent);

  Bart_LBL_F3_3 = TecGUILabelAdd(Form3_3Manager,
                               152,
                               59,
                    "Bart");
  AppleOrang_RADIO_F3_3 = TecGUIRadioBoxAdd(Form3_3Manager,
                                          982,
                                          239,
                                          1466,
                                          424,
                                 "Apples",
                                 "Oranges",
                                 (char *)NULL,
                                 (char *)NULL,
                                 (char *)NULL,
                                 AppleOrang_RADIO_F3_3_CB);
}

void BuildForm1_4(int  Parent)
{
  if (Form1_4Manager != BADDIALOGID)
    return;

  Form1_4Manager = TecGUIFormAddPage(Parent);

  Lisa_LBL_F1_4 = TecGUILabelAdd(Form1_4Manager,
                               318,
                               92,
                    "Lisa");
  AppleOrange_OPT_F1_4 = TecGUIOptionMenuAdd(Form1_4Manager,
                                           304,
                                           234,
                                           2392,
                                           168,
                        AppleOrange_OPT_F1_4_List,
                        AppleOrange_OPT_F1_4_CB);
}

void BuildForm2_4(int  Parent)
{
  if (Form2_4Manager != BADDIALOGID)
    return;

  Form2_4Manager = TecGUIFormAddPage(Parent);

  Maggie_LBL_F2_4 = TecGUILabelAdd(Form2_4Manager,
                                 290,
                                 70,
                    "Maggie");
  AppleOrange_SLST_F2_4 = TecGUIListAdd(Form2_4Manager,
                                      1313,
                                      125,
                                      1936,
                                      609,
                       0,
                       AppleOrange_SLST_F2_4_CB);
}

void BuildDialog7(int  ParentDialog)
{
  if (Dialog7Manager != BADDIALOGID)
    return;

  Dialog7Manager = TecGUIDialogCreateModal(ParentDialog,
                                          6586,
                                          1258,
                                          "Test Option Menus",
                                          Dialog7Init_CB,
                                          Dialog7OkButton_CB,
                                          NULL,
                                          Dialog7CancelButton_CB,
                                          Dialog7HelpButton_CB);
  Test_OPT_D7 = TecGUIOptionMenuAdd(Dialog7Manager,
                                  193,
                                  130,
                                  2503,
                                  168,
                        Test_OPT_D7_List,
                        Test_OPT_D7_CB);
  AppendItem_BTN_D7 = TecGUIButtonAdd(Dialog7Manager,
                                    1701,
                                    424,
                                    2780,
                                    152,
                    "<-- Append selection with",
                    AppendItem_BTN_D7_CB);
  AppendItem_TF_D7 = TecGUITextFieldAdd(Dialog7Manager,
                                      331,
                                      419,
                                      1244,
                                      152,
                       AppendItem_TF_D7_CB);
  DeleteAtPos_BTN_D7 = TecGUIButtonAdd(Dialog7Manager,
                                     331,
                                     822,
                                     2323,
                                     152,
                    "Delete Selected Item",
                    DeleteAtPos_BTN_D7_CB);
  ItemCount_BTN_D7 = TecGUIButtonAdd(Dialog7Manager,
                                   4481,
                                   1007,
                                   1936,
                                   152,
                    "Get Item Count...",
                    ItemCount_BTN_D7_CB);
  DeleteAll_BTN_D7 = TecGUIButtonAdd(Dialog7Manager,
                                   4481,
                                   800,
                                   1798,
                                   152,
                    "Delete All Items",
                    DeleteAll_BTN_D7_CB);
  GetString_BTN_D7 = TecGUIButtonAdd(Dialog7Manager,
                                   331,
                                   1040,
                                   2697,
                                   152,
                    "Get Selected Item String",
                    GetString_BTN_D7_CB);
  Replace_TF_D7 = TecGUITextFieldAdd(Dialog7Manager,
                                   331,
                                   626,
                                   1244,
                                   152,
                       Replace_TF_D7_CB);
  Replace_BTN_D7 = TecGUIButtonAdd(Dialog7Manager,
                                 1701,
                                 626,
                                 2835,
                                 152,
                    "<-- Replace selection with",
                    Replace_BTN_D7_CB);
}

void BuildDialog4(int  ParentDialog)
{
  if (Dialog4Manager != BADDIALOGID)
    return;

  Dialog4Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             6531,
                                             2831,
                                             "Form Test",
                                             Dialog4Init_CB,
                                             Dialog4CloseButton_CB,
                                             Dialog4HelpButton_CB);
  FM1_FM_D4 = TecGUIFormAdd(Dialog4Manager,
                          248,
                          147,
                          3457,
                          969);
  BuildForm1_3(FM1_FM_D4);
  BuildForm2_3(FM1_FM_D4);
  BuildForm3_3(FM1_FM_D4);
  FM2_FM_D4 = TecGUIFormAdd(Dialog4Manager,
                          262,
                          1187,
                          3402,
                          882);
  BuildForm1_4(FM2_FM_D4);
  BuildForm2_4(FM2_FM_D4);
  Homer_BTN_D4 = TecGUIButtonAdd(Dialog4Manager,
                               4287,
                               152,
                               1604,
                               152,
                    "Show Homer!",
                    Homer_BTN_D4_CB);
  Marge_BTN_D4 = TecGUIButtonAdd(Dialog4Manager,
                               4287,
                               413,
                               1562,
                               152,
                    "Show Marge!",
                    Marge_BTN_D4_CB);
  Bart_BTN_D4 = TecGUIButtonAdd(Dialog4Manager,
                              4287,
                              675,
                              1327,
                              152,
                    "Show Bart!",
                    Bart_BTN_D4_CB);
  Lisa_BTN_D4 = TecGUIButtonAdd(Dialog4Manager,
                              4287,
                              920,
                              1327,
                              152,
                    "Show Lisa!",
                    Lisa_BTN_D4_CB);
  Maggie_BTN_D4 = TecGUIButtonAdd(Dialog4Manager,
                                4287,
                                1192,
                                1659,
                                152,
                    "Show Maggie!",
                    Maggie_BTN_D4_CB);
  Clear_BTN_D4 = TecGUIButtonAdd(Dialog4Manager,
                               3845,
                               1917,
                               2296,
                               152,
                    "Clear output window",
                    Clear_BTN_D4_CB);
  Message_T_D4 = TecGUITextAdd(Dialog4Manager,
                             345,
                             2183,
                             5933,
                             517,
                       1,
                       NULL);
}

void BuildDialog8(int  ParentDialog)
{
  if (Dialog8Manager != BADDIALOGID)
    return;

  Dialog8Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             4383,
                                             951,
                                             "Test Scale Control",
                                             Dialog8Init_CB,
                                             Dialog8CloseButton_CB,
                                             Dialog8HelpButton_CB);
  TestScale_SC_D8 = TecGUIScaleAdd(Dialog8Manager,
                                 1521,
                                 533,
                                 1535,
                                 261,
                    0,
                    100,
                    0,
                    TestScale_SC_D8_CB,
                    TestScale_SCD_D8_CB);
  ShowDisplay_TOG_D8 = TecGUIToggleAdd(Dialog8Manager,
                                     401,
                                     157,
                                     2807,
                                     92,
                               "  Show Numeric Display",
                               ShowDisplay_TOG_D8_CB);
}

void BuildDialog9(int  ParentDialog)
{
  if (Dialog9Manager != BADDIALOGID)
    return;

  Dialog9Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             5094,
                                             342,
                                             "Test Spin Controls",
                                             Dialog9Init_CB,
                                             Dialog9CloseButton_CB,
                                             Dialog9HelpButton_CB);
  TestSpin_TFS_D9 = TecGUISpinTextFieldAdd(Dialog9Manager,
                                         3167,
                                         81,
                                         1396,
                                         152,
                       TestSpin_TFS_D9_ValueChanged_CB,
                       TestSpin_TFS_D9_ButtonUp_CB,
                       TestSpin_TFS_D9_ButtonDown_CB);
  Enteranumber_LBL_D9 = TecGUILabelAdd(Dialog9Manager,
                                     179,
                                     125,
                    "Enter a number from 1-100:");
}

void BuildDialog5(int  ParentDialog)
{
  if (Dialog5Manager != BADDIALOGID)
    return;

  Dialog5Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             4903,
                                             709,
                                             "Dialog Button Test",
                                             Dialog5Init_CB,
                                             Dialog5CloseButton_CB,
                                             Dialog5HelpButton_CB);
  Launch_BTN_D5 = TecGUIButtonAdd(Dialog5Manager,
                                1507,
                                495,
                                1867,
                                152,
                    "Launch Dialog...",
                    Launch_BTN_D5_CB);
  ActionArea_TOG_D5 = TecGUIToggleAdd(Dialog5Manager,
                                    387,
                                    59,
                                    3333,
                                    92,
                               "  Include Action Area Buttons",
                               ActionArea_TOG_D5_CB);
  Apply_TOG_D5 = TecGUIToggleAdd(Dialog5Manager,
                               387,
                               217,
                               2627,
                               92,
                               "  Include Apply Button",
                               Apply_TOG_D5_CB);
}

void BuildDialog6(int  ParentDialog)
{
  if (Dialog6Manager != BADDIALOGID)
    return;

  Dialog6Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             4383,
                                             1145,
                                             "Test Dialog",
                                             Dialog6Init_CB,
                                             Dialog6CloseButton_CB,
                                             Dialog6HelpButton_CB);
  ApplySen_TOG_D6 = TecGUIToggleAdd(Dialog6Manager,
                                  359,
                                  103,
                                  2973,
                                  92,
                               "  Apply button is sensitive",
                               ApplySen_TOG_D6_CB);
}

void BuildDialog1(int  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             9486,
                                             2831,
                                             "Tab Test",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             Dialog1HelpButton_CB);
  TAB1_TB_D1 = TecGUITabAdd(Dialog1Manager,
                          262,
                          250,
                          5394,
                          882,
                    TAB1_TBA_D1_CB,
                    TAB1_TBD_D1_CB);
  BuildTab1_1(TAB1_TB_D1);
  BuildTab2_1(TAB1_TB_D1);
  BuildTab3_1(TAB1_TB_D1);
  TAB2_TB_D1 = TecGUITabAdd(Dialog1Manager,
                          276,
                          1415,
                          5463,
                          789,
                    TAB2_TBA_D1_CB,
                    TAB2_TBD_D1_CB);
  BuildTab1_2(TAB2_TB_D1);
  BuildTab2_2(TAB2_TB_D1);
  Message_T_D1 = TecGUITextAdd(Dialog1Manager,
                             304,
                             2265,
                             8852,
                             517,
                       1,
                       NULL);
  Clear_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                               5933,
                               2047,
                               2296,
                               152,
                    "Clear output window",
                    Clear_BTN_D1_CB);
  ActiveTab_OPT_D1 = TecGUIOptionMenuAdd(Dialog1Manager,
                                       5809,
                                       250,
                                       2213,
                                       168,
                        ActiveTab_OPT_D1_List,
                        ActiveTab_OPT_D1_CB);
  Set_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                             8132,
                             261,
                             553,
                             152,
                    "Set",
                    Set_BTN_D1_CB);
}

void BuildTab1_1(int  Parent)
{
  if (Tab1_1Manager != BADDIALOGID)
    return;

  Tab1_1Manager = TecGUITabAddPage(Parent,
                               "Homer");
  Homertabpage_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                       318,
                                       103,
                    "Homer tab page");
  Apples_TOG_T1_1 = TecGUIToggleAdd(Tab1_1Manager,
                                  318,
                                  245,
                                  1161,
                                  92,
                               " Apples",
                               Apples_TOG_T1_1_CB);
  Oranges_TOG_T1_1 = TecGUIToggleAdd(Tab1_1Manager,
                                   318,
                                   359,
                                   1327,
                                   92,
                               " Oranges",
                               Oranges_TOG_T1_1_CB);
}

void BuildTab1_2(int  Parent)
{
  if (Tab1_2Manager != BADDIALOGID)
    return;

  Tab1_2Manager = TecGUITabAddPage(Parent,
                               "Lisa");
  AppleOrange_OPT_T1_2 = TecGUIOptionMenuAdd(Tab1_2Manager,
                                           179,
                                           212,
                                           2503,
                                           168,
                        AppleOrange_OPT_T1_2_List,
                        AppleOrange_OPT_T1_2_CB);
  Lisatabpage_LBL_T1_2 = TecGUILabelAdd(Tab1_2Manager,
                                      248,
                                      70,
                    "Lisa tab page");
}

void BuildTab2_2(int  Parent)
{
  if (Tab2_2Manager != BADDIALOGID)
    return;

  Tab2_2Manager = TecGUITabAddPage(Parent,
                               "Maggie");
  AppleOrange_SLST_T2_2 = TecGUIListAdd(Tab2_2Manager,
                                      2641,
                                      103,
                                      2282,
                                      609,
                       0,
                       AppleOrange_SLST_T2_2_CB);
  Maggietabpag_LBL_T2_2 = TecGUILabelAdd(Tab2_2Manager,
                                       262,
                                       70,
                    "Maggie tab page");
}

void BuildTab2_1(int  Parent)
{
  if (Tab2_1Manager != BADDIALOGID)
    return;

  Tab2_1Manager = TecGUITabAddPage(Parent,
                               "Marge");
  Apples_BTN_T2_1 = TecGUIButtonAdd(Tab2_1Manager,
                                  331,
                                  190,
                                  912,
                                  152,
                    "Apples",
                    Apples_BTN_T2_1_CB);
  Margetabpage_LBL_T2_1 = TecGUILabelAdd(Tab2_1Manager,
                                       331,
                                       76,
                    "Marge tab page");
  Oranges_BTN_T2_1 = TecGUIButtonAdd(Tab2_1Manager,
                                   331,
                                   392,
                                   1078,
                                   152,
                    "Oranges",
                    Oranges_BTN_T2_1_CB);
}

void BuildTab3_1(int  Parent)
{
  if (Tab3_1Manager != BADDIALOGID)
    return;

  Tab3_1Manager = TecGUITabAddPage(Parent,
                               "Bart");
  Barttabpage_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                                      401,
                                      103,
                    "Bart tab page");
  AppleOrang_RADIO_T3_1 = TecGUIRadioBoxAdd(Tab3_1Manager,
                                          2060,
                                          239,
                                          1466,
                                          424,
                                 "Apples",
                                 "Oranges",
                                 (char *)NULL,
                                 (char *)NULL,
                                 (char *)NULL,
                                 AppleOrang_RADIO_T3_1_CB);
}

void InitTGB(void)
{
/* Currently not used */
}
