/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern int  Form1_3Manager;
extern void BuildForm1_3(int  Parent);

extern int  Homer_LBL_F1_3;
extern int  Apples_TOG_F1_3;
extern int  Oranges_TOG_F1_3;
extern int  Form2_3Manager;
extern void BuildForm2_3(int  Parent);

extern int  Marge_LBL_F2_3;
extern int  Apples_BTN_F2_3;
extern int  Oranges_BTN_F2_3;
extern int  Form3_3Manager;
extern void BuildForm3_3(int  Parent);

extern int  Bart_LBL_F3_3;
extern int  AppleOrang_RADIO_F3_3;
extern int  Form1_4Manager;
extern void BuildForm1_4(int  Parent);

extern int  Lisa_LBL_F1_4;
extern int  AppleOrange_OPT_F1_4;
extern int  Form2_4Manager;
extern void BuildForm2_4(int  Parent);

extern int  Maggie_LBL_F2_4;
extern int  AppleOrange_SLST_F2_4;
extern int  Dialog7Manager;
extern void BuildDialog7(int  ParentDialog);

extern int  Test_OPT_D7;
extern int  AppendItem_BTN_D7;
extern int  AppendItem_TF_D7;
extern int  DeleteAtPos_BTN_D7;
extern int  ItemCount_BTN_D7;
extern int  DeleteAll_BTN_D7;
extern int  GetString_BTN_D7;
extern int  Replace_TF_D7;
extern int  Replace_BTN_D7;
extern int  Dialog4Manager;
extern void BuildDialog4(int  ParentDialog);

extern int  FM1_FM_D4;
extern int  FM2_FM_D4;
extern int  Homer_BTN_D4;
extern int  Marge_BTN_D4;
extern int  Bart_BTN_D4;
extern int  Lisa_BTN_D4;
extern int  Maggie_BTN_D4;
extern int  Clear_BTN_D4;
extern int  Message_T_D4;
extern int  Dialog8Manager;
extern void BuildDialog8(int  ParentDialog);

extern int  TestScale_SC_D8;
extern int  ShowDisplay_TOG_D8;
extern int  Dialog9Manager;
extern void BuildDialog9(int  ParentDialog);

extern int  TestSpin_TFS_D9;
extern int  Enteranumber_LBL_D9;
extern int  Dialog5Manager;
extern void BuildDialog5(int  ParentDialog);

extern int  Launch_BTN_D5;
extern int  ActionArea_TOG_D5;
extern int  Apply_TOG_D5;
extern int  Dialog6Manager;
extern void BuildDialog6(int  ParentDialog);

extern int  ApplySen_TOG_D6;
extern int  Dialog1Manager;
extern void BuildDialog1(int  ParentDialog);

extern int  TAB1_TB_D1;
extern int  TAB2_TB_D1;
extern int  Message_T_D1;
extern int  Clear_BTN_D1;
extern int  ActiveTab_OPT_D1;
extern int  Set_BTN_D1;
extern int  Tab1_1Manager;
extern void BuildTab1_1(int  Parent);

extern int  Homertabpage_LBL_T1_1;
extern int  Apples_TOG_T1_1;
extern int  Oranges_TOG_T1_1;
extern int  Tab1_2Manager;
extern void BuildTab1_2(int  Parent);

extern int  AppleOrange_OPT_T1_2;
extern int  Lisatabpage_LBL_T1_2;
extern int  Tab2_2Manager;
extern void BuildTab2_2(int  Parent);

extern int  AppleOrange_SLST_T2_2;
extern int  Maggietabpag_LBL_T2_2;
extern int  Tab2_1Manager;
extern void BuildTab2_1(int  Parent);

extern int  Apples_BTN_T2_1;
extern int  Margetabpage_LBL_T2_1;
extern int  Oranges_BTN_T2_1;
extern int  Tab3_1Manager;
extern void BuildTab3_1(int  Parent);

extern int  Barttabpage_LBL_T3_1;
extern int  AppleOrang_RADIO_T3_1;
