/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#include "TECADDON.h"
#include "GUIDEFS.h"
int Form1_3Manager = BADDIALOGID;
int Homer_LBL_F1_3 = BADDIALOGID;
int Apples_TOG_F1_3 = BADDIALOGID;
int Oranges_TOG_F1_3 = BADDIALOGID;
int Form2_3Manager = BADDIALOGID;
int Marge_LBL_F2_3 = BADDIALOGID;
int Apples_BTN_F2_3 = BADDIALOGID;
int Oranges_BTN_F2_3 = BADDIALOGID;
int Form3_3Manager = BADDIALOGID;
int Bart_LBL_F3_3 = BADDIALOGID;
int AppleOrang_RADIO_F3_3 = BADDIALOGID;
int Form1_4Manager = BADDIALOGID;
int Lisa_LBL_F1_4 = BADDIALOGID;
int AppleOrange_OPT_F1_4 = BADDIALOGID;
int Form2_4Manager = BADDIALOGID;
int Maggie_LBL_F2_4 = BADDIALOGID;
int AppleOrange_SLST_F2_4 = BADDIALOGID;
int Dialog7Manager = BADDIALOGID;
int Test_OPT_D7 = BADDIALOGID;
int AppendItem_BTN_D7 = BADDIALOGID;
int AppendItem_TF_D7 = BADDIALOGID;
int DeleteAtPos_BTN_D7 = BADDIALOGID;
int ItemCount_BTN_D7 = BADDIALOGID;
int DeleteAll_BTN_D7 = BADDIALOGID;
int GetString_BTN_D7 = BADDIALOGID;
int Replace_TF_D7 = BADDIALOGID;
int Replace_BTN_D7 = BADDIALOGID;
int Dialog4Manager = BADDIALOGID;
int FM1_FM_D4 = BADDIALOGID;
int FM2_FM_D4 = BADDIALOGID;
int Homer_BTN_D4 = BADDIALOGID;
int Marge_BTN_D4 = BADDIALOGID;
int Bart_BTN_D4 = BADDIALOGID;
int Lisa_BTN_D4 = BADDIALOGID;
int Maggie_BTN_D4 = BADDIALOGID;
int Clear_BTN_D4 = BADDIALOGID;
int Message_T_D4 = BADDIALOGID;
int Dialog8Manager = BADDIALOGID;
int TestScale_SC_D8 = BADDIALOGID;
int ShowDisplay_TOG_D8 = BADDIALOGID;
int Dialog9Manager = BADDIALOGID;
int TestSpin_TFS_D9 = BADDIALOGID;
int Enteranumber_LBL_D9 = BADDIALOGID;
int Dialog5Manager = BADDIALOGID;
int Launch_BTN_D5 = BADDIALOGID;
int ActionArea_TOG_D5 = BADDIALOGID;
int Apply_TOG_D5 = BADDIALOGID;
int Dialog6Manager = BADDIALOGID;
int ApplySen_TOG_D6 = BADDIALOGID;
int Dialog1Manager = BADDIALOGID;
int TAB1_TB_D1 = BADDIALOGID;
int TAB2_TB_D1 = BADDIALOGID;
int Message_T_D1 = BADDIALOGID;
int Clear_BTN_D1 = BADDIALOGID;
int ActiveTab_OPT_D1 = BADDIALOGID;
int Set_BTN_D1 = BADDIALOGID;
int Tab1_1Manager = BADDIALOGID;
int Homertabpage_LBL_T1_1 = BADDIALOGID;
int Apples_TOG_T1_1 = BADDIALOGID;
int Oranges_TOG_T1_1 = BADDIALOGID;
int Tab1_2Manager = BADDIALOGID;
int AppleOrange_OPT_T1_2 = BADDIALOGID;
int Lisatabpage_LBL_T1_2 = BADDIALOGID;
int Tab2_2Manager = BADDIALOGID;
int AppleOrange_SLST_T2_2 = BADDIALOGID;
int Maggietabpag_LBL_T2_2 = BADDIALOGID;
int Tab2_1Manager = BADDIALOGID;
int Apples_BTN_T2_1 = BADDIALOGID;
int Margetabpage_LBL_T2_1 = BADDIALOGID;
int Oranges_BTN_T2_1 = BADDIALOGID;
int Tab3_1Manager = BADDIALOGID;
int Barttabpage_LBL_T3_1 = BADDIALOGID;
int AppleOrang_RADIO_T3_1 = BADDIALOGID;
