/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             3673,
                                             3004,
                                             "Advanced Quick Edit Tool",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             Dialog1HelpButton_CB);
  TecGUIFrameAdd(Dialog1Manager,
             208,
             93,
             3236,
             959,
                    "Coord Sys/Char Height");

  TecGUIFrameAdd(Dialog1Manager,
             208,
             1645,
             3222,
             802,
                    "Text Anchor Location");

  Text_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             2111,
                             168,
                    "Text:");

  Geometry_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                 319,
                                 168,
                    "Geometry:");

  Left_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             638,
                             2313,
                    "Left");

  Cntr_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             1402,
                             2313,
                    "Cntr");

  Right_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                              2152,
                              2313,
                    "Right");

  Head_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             2750,
                             1784,
                    "Head");

  Mid_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                            2750,
                            1959,
                    "Mid");

  Base_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             2750,
                             2139,
                    "Base");

  Attachment_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                   236,
                                   2761,
                    "Attachment:");

  Scope_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                              222,
                              2558,
                    "Scope:");

  GeomFPB_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                 375,
                                 290,
                                 888,
                                 145,
                    "Frame",
                    GeomFPB_BTN_D1_CB);

  GeomGPB_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                 375,
                                 470,
                                 888,
                                 145,
                    "Grid ",
                    GeomGPB_BTN_D1_CB);

  TextFFPB_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                  1527,
                                  290,
                                  1722,
                                  145,
                    "Frame/Frame",
                    TextFFPB_BTN_D1_CB);

  TextFPPB_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                  1527,
                                  465,
                                  1722,
                                  145,
                    "Frame/Point",
                    TextFPPB_BTN_D1_CB);

  TextGGPB_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                  1527,
                                  645,
                                  1722,
                                  145,
                    "Grid/Grid  ",
                    TextGGPB_BTN_D1_CB);

  TextGFPB_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                  1527,
                                  819,
                                  1722,
                                  145,
                    "Grid/Frame ",
                    TextGFPB_BTN_D1_CB);

  TextHLPB_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                  541,
                                  1744,
                                  611,
                                  145,
                    "   ",
                    TextHLPB_BTN_D1_CB);

  TextHCPB_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                  1305,
                                  1744,
                                  611,
                                  145,
                    "   ",
                    TextHCPB_BTN_D1_CB);

  TextHRPB_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                  2041,
                                  1744,
                                  611,
                                  145,
                    "   ",
                    TextHRPB_BTN_D1_CB);

  TextMLPB_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                  541,
                                  1918,
                                  611,
                                  145,
                    "   ",
                    TextMLPB_BTN_D1_CB);

  TextMCPB_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                  1305,
                                  1918,
                                  611,
                                  145,
                    "   ",
                    TextMCPB_BTN_D1_CB);

  TextMRPB_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                  2041,
                                  1918,
                                  611,
                                  145,
                    "   ",
                    TextMRPB_BTN_D1_CB);

  TextBLPB_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                  541,
                                  2098,
                                  611,
                                  145,
                    "   ",
                    TextBLPB_BTN_D1_CB);

  TextBCPB_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                  1305,
                                  2098,
                                  611,
                                  145,
                    "   ",
                    TextBCPB_BTN_D1_CB);

  TextBRPB_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                  2055,
                                  2098,
                                  611,
                                  145,
                    "   ",
                    TextBRPB_BTN_D1_CB);

  ScopeLPB_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                  1291,
                                  2505,
                                  1027,
                                  145,
                    "Local ",
                    ScopeLPB_BTN_D1_CB);

  ScopeGPB_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                  2388,
                                  2505,
                                  1027,
                                  145,
                    "Global",
                    ScopeGPB_BTN_D1_CB);

  Select_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                2388,
                                2709,
                                1027,
                                145,
                    "Select... ",
                    Select_BTN_D1_CB);

  TextBoxMargi_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                      222,
                                      1116,
                                      2805,
                                      145,
                    "Text Box Margin...  ",
                    TextBoxMargi_BTN_D1_CB);

  TextLineSpac_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                      222,
                                      1337,
                                      2805,
                                      145,
                    "Text Line Spacing...",
                    TextLineSpac_BTN_D1_CB);

}

/**
 */
void BuildDialog3(LgIndex_t  ParentDialog)
{
  if (Dialog3Manager != BADDIALOGID)
    return;

  Dialog3Manager = TecGUIDialogCreateModal(ParentDialog,
                                          4780,
                                          669,
                                          "Enter Text Box Margin",
                                          Dialog3Init_CB,
                                          Dialog3OkButton_CB,
                                          NULL,
                                          Dialog3CancelButton_CB,
                                          Dialog3HelpButton_CB);
  Enterthenewt_LBL_D3 = TecGUILabelAdd(Dialog3Manager,
                                     236,
                                     127,
                    "Enter the new text box margin:");

  TextBoxMargin_TF_D3 = TecGUITextFieldAdd(Dialog3Manager,
                                         375,
                                         325,
                                         4111,
                                         145,
                       TextBoxMargin_TF_D3_CB);

}

/**
 */
void BuildDialog4(LgIndex_t  ParentDialog)
{
  if (Dialog4Manager != BADDIALOGID)
    return;

  Dialog4Manager = TecGUIDialogCreateModal(ParentDialog,
                                          4780,
                                          669,
                                          "Enter Text Line Spacing",
                                          Dialog4Init_CB,
                                          Dialog4OkButton_CB,
                                          NULL,
                                          Dialog4CancelButton_CB,
                                          Dialog4HelpButton_CB);
  Enterthenewt_LBL_D4 = TecGUILabelAdd(Dialog4Manager,
                                     236,
                                     87,
                    "Enter the new text line spacing:");

  TextLineSpaci_TF_D4 = TecGUITextFieldAdd(Dialog4Manager,
                                         375,
                                         284,
                                         4111,
                                         145,
                       TextLineSpaci_TF_D4_CB);

}

/**
 */
void BuildDialog2(LgIndex_t  ParentDialog)
{
  if (Dialog2Manager != BADDIALOGID)
    return;

  Dialog2Manager = TecGUIDialogCreateModal(ParentDialog,
                                          4780,
                                          1561,
                                          "Attachment Selection",
                                          Dialog2Init_CB,
                                          Dialog2OkButton_CB,
                                          NULL,
                                          Dialog2CancelButton_CB,
                                          Dialog2HelpButton_CB);
  ZoneOrMapLi_SLST_D2 = TecGUIListAdd(Dialog2Manager,
                                    375,
                                    348,
                                    4097,
                                    1052,
                       0,
                       ZoneOrMapLi_SLST_D2_CB);

  SelectAttach_LBL_D2 = TecGUILabelAdd(Dialog2Manager,
                                     236,
                                     133,
                    "Select Attachment:");

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
