/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#include "TECADDON.h"
#include "GUIDEFS.h"
LgIndex_t Dialog1Manager = BADDIALOGID;
LgIndex_t Text_LBL_D1 = BADDIALOGID;
LgIndex_t Geometry_LBL_D1 = BADDIALOGID;
LgIndex_t Left_LBL_D1 = BADDIALOGID;
LgIndex_t Cntr_LBL_D1 = BADDIALOGID;
LgIndex_t Right_LBL_D1 = BADDIALOGID;
LgIndex_t Head_LBL_D1 = BADDIALOGID;
LgIndex_t Mid_LBL_D1 = BADDIALOGID;
LgIndex_t Base_LBL_D1 = BADDIALOGID;
LgIndex_t Attachment_LBL_D1 = BADDIALOGID;
LgIndex_t Scope_LBL_D1 = BADDIALOGID;
LgIndex_t GeomFPB_BTN_D1 = BADDIALOGID;
LgIndex_t GeomGPB_BTN_D1 = BADDIALOGID;
LgIndex_t TextFFPB_BTN_D1 = BADDIALOGID;
LgIndex_t TextFPPB_BTN_D1 = BADDIALOGID;
LgIndex_t TextGGPB_BTN_D1 = BADDIALOGID;
LgIndex_t TextGFPB_BTN_D1 = BADDIALOGID;
LgIndex_t TextHLPB_BTN_D1 = BADDIALOGID;
LgIndex_t TextHCPB_BTN_D1 = BADDIALOGID;
LgIndex_t TextHRPB_BTN_D1 = BADDIALOGID;
LgIndex_t TextMLPB_BTN_D1 = BADDIALOGID;
LgIndex_t TextMCPB_BTN_D1 = BADDIALOGID;
LgIndex_t TextMRPB_BTN_D1 = BADDIALOGID;
LgIndex_t TextBLPB_BTN_D1 = BADDIALOGID;
LgIndex_t TextBCPB_BTN_D1 = BADDIALOGID;
LgIndex_t TextBRPB_BTN_D1 = BADDIALOGID;
LgIndex_t ScopeLPB_BTN_D1 = BADDIALOGID;
LgIndex_t ScopeGPB_BTN_D1 = BADDIALOGID;
LgIndex_t Select_BTN_D1 = BADDIALOGID;
LgIndex_t TextBoxMargi_BTN_D1 = BADDIALOGID;
LgIndex_t TextLineSpac_BTN_D1 = BADDIALOGID;
LgIndex_t Dialog3Manager = BADDIALOGID;
LgIndex_t Enterthenewt_LBL_D3 = BADDIALOGID;
LgIndex_t TextBoxMargin_TF_D3 = BADDIALOGID;
LgIndex_t Dialog4Manager = BADDIALOGID;
LgIndex_t Enterthenewt_LBL_D4 = BADDIALOGID;
LgIndex_t TextLineSpaci_TF_D4 = BADDIALOGID;
LgIndex_t Dialog2Manager = BADDIALOGID;
LgIndex_t ZoneOrMapLi_SLST_D2 = BADDIALOGID;
LgIndex_t SelectAttach_LBL_D2 = BADDIALOGID;
