/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern LgIndex_t Dialog1Manager;
extern void BuildDialog1(LgIndex_t  ParentDialog);

extern LgIndex_t  Text_LBL_D1;
extern LgIndex_t  Geometry_LBL_D1;
extern LgIndex_t  Left_LBL_D1;
extern LgIndex_t  Cntr_LBL_D1;
extern LgIndex_t  Right_LBL_D1;
extern LgIndex_t  Head_LBL_D1;
extern LgIndex_t  Mid_LBL_D1;
extern LgIndex_t  Base_LBL_D1;
extern LgIndex_t  Attachment_LBL_D1;
extern LgIndex_t  Scope_LBL_D1;
extern LgIndex_t  GeomFPB_BTN_D1;
extern LgIndex_t  GeomGPB_BTN_D1;
extern LgIndex_t  TextFFPB_BTN_D1;
extern LgIndex_t  TextFPPB_BTN_D1;
extern LgIndex_t  TextGGPB_BTN_D1;
extern LgIndex_t  TextGFPB_BTN_D1;
extern LgIndex_t  TextHLPB_BTN_D1;
extern LgIndex_t  TextHCPB_BTN_D1;
extern LgIndex_t  TextHRPB_BTN_D1;
extern LgIndex_t  TextMLPB_BTN_D1;
extern LgIndex_t  TextMCPB_BTN_D1;
extern LgIndex_t  TextMRPB_BTN_D1;
extern LgIndex_t  TextBLPB_BTN_D1;
extern LgIndex_t  TextBCPB_BTN_D1;
extern LgIndex_t  TextBRPB_BTN_D1;
extern LgIndex_t  ScopeLPB_BTN_D1;
extern LgIndex_t  ScopeGPB_BTN_D1;
extern LgIndex_t  Select_BTN_D1;
extern LgIndex_t  TextBoxMargi_BTN_D1;
extern LgIndex_t  TextLineSpac_BTN_D1;
extern LgIndex_t Dialog3Manager;
extern void BuildDialog3(LgIndex_t  ParentDialog);

extern LgIndex_t  Enterthenewt_LBL_D3;
extern LgIndex_t  TextBoxMargin_TF_D3;
extern LgIndex_t Dialog4Manager;
extern void BuildDialog4(LgIndex_t  ParentDialog);

extern LgIndex_t  Enterthenewt_LBL_D4;
extern LgIndex_t  TextLineSpaci_TF_D4;
extern LgIndex_t Dialog2Manager;
extern void BuildDialog2(LgIndex_t  ParentDialog);

extern LgIndex_t  ZoneOrMapLi_SLST_D2;
extern LgIndex_t  SelectAttach_LBL_D2;
