/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern int  Dialog1Manager;
extern void BuildDialog1(int  ParentDialog);

extern int  Thetotalis00_LBL_D1;
