/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern LgIndex_t Dialog1Manager;
extern void BuildDialog1(LgIndex_t  ParentDialog);

extern LgIndex_t  ISkip_LBL_D1;
extern LgIndex_t  Filename_LBL_D1;
extern LgIndex_t  Delimeter_RADIO_D1;
extern LgIndex_t  ISkip_TF_D1;
extern LgIndex_t  FileName_TF_D1;
extern LgIndex_t  SelectFile_BTN_D1;
extern LgIndex_t  Delimeter_LBL_D1;
