      EXTERNAL Sidebar1Activate_CB
      !DEC$ attributes C::Sidebar1Activate_CB
      EXTERNAL Sidebar1Deactivate_CB
      !DEC$ attributes C::Sidebar1Deactivate_CB
      EXTERNAL ZoomIn_BTN_S1_CB
      !DEC$ attributes C::ZoomIn_BTN_S1_CB
      EXTERNAL BTN14_BTN_S1_CB
      !DEC$ attributes C::BTN14_BTN_S1_CB
      EXTERNAL BTN13_BTN_S1_CB
      !DEC$ attributes C::BTN13_BTN_S1_CB
      EXTERNAL BTN12_BTN_S1_CB
      !DEC$ attributes C::BTN12_BTN_S1_CB
      EXTERNAL BTN11_BTN_S1_CB
      !DEC$ attributes C::BTN11_BTN_S1_CB
      EXTERNAL BTN10_BTN_S1_CB
      !DEC$ attributes C::BTN10_BTN_S1_CB
      EXTERNAL BTN9_BTN_S1_CB
      !DEC$ attributes C::BTN9_BTN_S1_CB
      EXTERNAL BTN8_BTN_S1_CB
      !DEC$ attributes C::BTN8_BTN_S1_CB
      EXTERNAL BTN7_BTN_S1_CB
      !DEC$ attributes C::BTN7_BTN_S1_CB
      EXTERNAL BTN6_BTN_S1_CB
      !DEC$ attributes C::BTN6_BTN_S1_CB
      EXTERNAL BTN5_BTN_S1_CB
      !DEC$ attributes C::BTN5_BTN_S1_CB
      EXTERNAL Scatter_BTN_S1_CB
      !DEC$ attributes C::Scatter_BTN_S1_CB
      EXTERNAL Contour_BTN_S1_CB
      !DEC$ attributes C::Contour_BTN_S1_CB
      EXTERNAL Alter_BTN_S1_CB
      !DEC$ attributes C::Alter_BTN_S1_CB
      EXTERNAL Data_BTN_S1_CB
      !DEC$ attributes C::Data_BTN_S1_CB
      EXTERNAL ZoomOut_BTN_S1_CB
      !DEC$ attributes C::ZoomOut_BTN_S1_CB
