/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern LgIndex_t Dialog1Manager;
extern void BuildDialog1(LgIndex_t  ParentDialog);

extern LgIndex_t  Zone_OPT_D1;
extern LgIndex_t  Variable_OPT_D1;
extern LgIndex_t  Zone_LBL_D1;
extern LgIndex_t  Variable_LBL_D1;
extern LgIndex_t  Numberofpoin_LBL_D1;
extern LgIndex_t  NumPoints_LBL_D1;
extern LgIndex_t  LocationLabe_LBL_D1;
extern LgIndex_t  Location_LBL_D1;
extern LgIndex_t  FieldDataTyp_LBL_D1;
extern LgIndex_t  FDType_LBL_D1;
extern LgIndex_t  I_OPT_D1;
extern LgIndex_t  I_LBL_D1;
extern LgIndex_t  J_OPT_D1;
extern LgIndex_t  J_LBL_D1;
extern LgIndex_t  K_OPT_D1;
extern LgIndex_t  K_LBL_D1;
extern LgIndex_t  Value_LBL_D1;
extern LgIndex_t  Value_TF_D1;
extern LgIndex_t  Set_BTN_D1;
