/*
 *
 * NOTE: This file automatically generated by the Tecplot GUI Builder.
 *       Do not edit this file!
 *
 */

$$IF(AW_ISMODAL)
/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;
  Dialog1Manager = TecGUIDialogCreateModal(ParentDialog,
                                           4383,
                                           2250,
                                           "$$AW_DLGTITLE$$",
                                           Dialog1Init_CB,
                                           Dialog1OkButton_CB,
                                           NULL, /* ApplyButtonCallback */
                                           Dialog1CancelButton_CB,
                                           Dialog1HelpButton_CB);
}
$$ENDIF

$$IF(AW_ISMODELESS)
/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;
  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                              4383,
                                              2250,
                                              "$$AW_DLGTITLE$$",
                                              Dialog1Init_CB,
                                              Dialog1CloseButton_CB,
                                              Dialog1HelpButton_CB);
}
$$ENDIF

$$IF(AW_HASSIDEBAR)
/**
 */
void BuildSidebar1(void)
{
  if (Sidebar1Manager != BADDIALOGID)
    return;
  Sidebar1Manager = TecGUISidebarRegister("$$AW_SBTITLE$$",
                                          AddOnID,
                                          2240,
                                          3068,
                                          Sidebar1Activate_CB,
                                          Sidebar1Deactivate_CB);
}
$$ENDIF

/**
 */
void InitTGB(void)
{
$$IF(AW_ISMODAL)
  Dialog1Manager = BADDIALOGID;
$$ENDIF
$$IF(AW_ISMODELESS)
  Dialog1Manager = BADDIALOGID;
$$ENDIF
$$IF(AW_HASSIDEBAR)
  Sidebar1Manager = BADDIALOGID;
$$ENDIF
}
