$$IF(MFCDLL)
#include "stdafx.h"
$$ENDIF
/*
 *
 * NOTE: This file automatically generated by the Tecplot GUI Builder.
 *       Do not edit this file!
 *
 */
#include "TECADDON.h"
#include "GUIDEFS.h"

$$IF(AW_ISMODAL)
LgIndex_t  Dialog1Manager = BADDIALOGID;
$$ENDIF
$$IF(AW_ISMODELESS)
LgIndex_t  Dialog1Manager = BADDIALOGID;
$$ENDIF
$$IF(AW_HASSIDEBAR)
LgIndex_t  Sidebar1Manager = BADDIALOGID;
$$ENDIF
