/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern int  Dialog1Manager;
extern void BuildDialog1(int  ParentDialog);

extern int  File_LBL_D1;
extern int  FileName_TF_D1;
extern int  BrowseFile_BTN_D1;
extern int  Depth_RADIO_D1;
extern int  ImageWidthin_LBL_D1;
extern int  ImageWidth_TF_D1;
extern int  ExportRegion_OPT_D1;
extern int  ExportRegion_LBL_D1;
