/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#include "TECADDON.h"
#include "GUIDEFS.h"
int Dialog1Manager = BADDIALOGID;
int File_LBL_D1 = BADDIALOGID;
int FileName_TF_D1 = BADDIALOGID;
int BrowseFile_BTN_D1 = BADDIALOGID;
int Depth_RADIO_D1 = BADDIALOGID;
int ImageWidthin_LBL_D1 = BADDIALOGID;
int ImageWidth_TF_D1 = BADDIALOGID;
int ExportRegion_OPT_D1 = BADDIALOGID;
int ExportRegion_LBL_D1 = BADDIALOGID;
