/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             3212,
                                             613,
                                             "Create FE Sub-Zone",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             Dialog1HelpButton_CB);
  Create_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                1107,
                                218,
                                865,
                                143,
                    "Create",
                    Create_BTN_D1_CB);

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
