/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             4667,
                                             843,
                                             "Set Style",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             Dialog1HelpButton_CB);
  ShowMesh_TOG_D1 = TecGUIToggleAdd(Dialog1Manager,
                                  280,
                                  47,
                                  1922,
                                  127,
                               "Show Mesh",
                               ShowMesh_TOG_D1_CB);

  ShowContour_TOG_D1 = TecGUIToggleAdd(Dialog1Manager,
                                     292,
                                     191,
                                     2177,
                                     127,
                               "Show Contour",
                               ShowContour_TOG_D1_CB);

  ResetContour_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                      280,
                                      405,
                                      2381,
                                      143,
                    "Reset Contour Levels",
                    ResetContour_BTN_D1_CB);

  NumLevels_TF_D1 = TecGUITextFieldAdd(Dialog1Manager,
                                     2814,
                                     405,
                                     878,
                                     143,
                       NumLevels_TF_D1_CB);

  Levels_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                               3794,
                               447,
                    "Levels");

  MeshColor_OPT_D1 = TecGUIOptionMenuAdd(Dialog1Manager,
                                       1642,
                                       639,
                                       1884,
                                       143,
                        MeshColor_OPT_D1_List,
                        MeshColor_OPT_D1_CB);

  MeshColor_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                  280,
                                  676,
                    "Mesh Color:");

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
