/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#include "TECADDON.h"
#include "GUIDEFS.h"
LgIndex_t Dialog1Manager = BADDIALOGID;
LgIndex_t ShowMesh_TOG_D1 = BADDIALOGID;
LgIndex_t ShowContour_TOG_D1 = BADDIALOGID;
LgIndex_t ResetContour_BTN_D1 = BADDIALOGID;
LgIndex_t NumLevels_TF_D1 = BADDIALOGID;
LgIndex_t Levels_LBL_D1 = BADDIALOGID;
LgIndex_t MeshColor_OPT_D1 = BADDIALOGID;
LgIndex_t MeshColor_LBL_D1 = BADDIALOGID;
