/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


void BuildDialog1(int  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             3891,
                                             1710,
                                             "Animate I Planes",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             Dialog1HelpButton_CB);
  Zones_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                              394,
                              111,
                    "Zone(s)");
  ZoneList_MLST_D1 = TecGUIListAdd(Dialog1Manager,
                                 674,
                                 250,
                                 2152,
                                 788,
                       1,
                       ZoneList_MLST_D1_CB);
  Skip_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             585,
                             1194,
                    "Skip");
  Skip_TF_D1 = TecGUITextFieldAdd(Dialog1Manager,
                                1247,
                                1146,
                                955,
                                154,
                       Skip_TF_D1_CB);
  AnimPlanes_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                    980,
                                    1423,
                                    1922,
                                    154,
                    "Animate I Planes",
                    AnimPlanes_BTN_D1_CB);
}

void InitTGB(void)
{
/* Currently not used */
}
