C   ***************************************************
C   *                                                 *
C   *  NOTE!  This file is automatically built by     *
C   *         the Tecplot GUI Builder.  It is highly  *
C   *         recommended that you never edit this    *
C   *         file directly!                          *
C   *                                                 *
C   ***************************************************


      Parameter (BADDIALOGID=-2,MAINDIALOGID=-1)
      COMMON /Dialog1Manager_C/ Dialog1Manager
      INTEGER*4 Dialog1Manager
      COMMON /Reset_BTN_D1_C/ Reset_BTN_D1
      INTEGER*4 Reset_BTN_D1
      COMMON /AmpScale_SC_D1_C/ AmpScale_SC_D1
      INTEGER*4 AmpScale_SC_D1
      COMMON /AmplitudeShi_LBL_D1_C/ AmplitudeShi_LBL_D1
      INTEGER*4 AmplitudeShi_LBL_D1
